#!/bin/bash
#
# Complete job archiver for 
# umbrella sampling MD runs
#
# expects a directory structure like
# `-- US2
#    |-- delta
#    |   |-- rep1
#    |   |   `-- runfiles
#    |   |-- rep2
#    |   |   `-- runfiles
#    |   |-- rep3
#    |   |   `-- runfiles
#    |   |-- rep4
#    |   |   `-- runfiles
#    |   `-- rep5
#    |       `-- runfiles
#    `-- wt
#        |-- rep1
#        |   `-- runfiles
#        |-- rep2
#        |   `-- runfiles
#        |-- rep3
#        |   `-- runfiles
#        |-- rep4
#        |   `-- runfiles
#        `-- rep5
#            `-- runfiles
#
#
# Generally, this script identifies all NAMD output files
# for any completed runs ('End' found at end of log), 
# saving these file names in to a 'listfile', and then
# generates a new tar archive using only those files listed
# in the listfile.  Initially, the listfile is called 'dones'.
#
# A NAMD run is signified by the presence of a NAMD config file
# whose name conforms to "*_frm[0-9]*.namd", and it is deemed 
# complete if the log file for that run has 'End' at the end.
# All files generated by NAMD for a run have the 
# prefix "*_frm[0-9]*-run.", including dcd, colvar.traj, coor, 
# and xsc files.
#
# If no listfile with name matching "dones*" is found, it is assumed
# this is the first time the script is being run; it
# creates the listfile "dones" and populates with list of NAMD output 
# files to be archived.
#
# If one or more file with name matching "dones*"" is found,
# it is assumed this script has been run at least once previously. 
# It takes last line of the latest listfile as the name of a file
# that sets the earliest modification time for any file to be considered
# for addition to a new archive.  These file names are saved to a
# new listfile.  The name of this listfile is either "dones.1"
# if only "dones" is found, or "dones.#" where "#" is the next
# integer.
#
# This script is meant to be run many times in series in order
# to generate tar archives of completed runs without doubly-
# archiving any one file.

OWD=`pwd`
# grab the newest listfile
unset -v latest
for file in dones*; do
  [[ $file -nt $latest ]] && latest=$file
done
if [[ -v latest ]]; then
    # a listfile is identified, take the last entry
    lastone=`tail -1 $latest`
    lastonepath=${OWD}/${lastone}
    echo "Using last entry in $latest ..."
    if [[ "$latest" == "${latest%.*}" ]]; then
        # no integer extension -- start with 1!
        saveme=${latest}.1
    else
        # integer extension -- increment it!
        num="${latest##*.}"
        num=$((num+1))
        saveme="dones.${num}"
    fi
else
    # first-time run
    saveme='dones'
    lastonepath='NONE'
fi

savemepath=${OWD}/${saveme}

echo "Writing names of files to be archived to $saveme"

touch $savemepath
for t in US2/wt US2/delta; do
    cd $t
    T=${t##*/}
    for d in rep?; do
	    R=${d##*rep}
        cd $d/runfiles
	    for r in `echo *_frm[0-9]*namd`; do
            pref=${r%.namd}
	        if [[ -f ${pref}.log ]] ; then
                if [ $lastonepath == "NONE" -o ${pref}.log -nt $lastonepath ]; then
                    done=`tail -4 ${pref}.log | grep -c End`
                    if [[ $done == "1" ]]; then
                        echo $t/$d/runfiles/${pref}.log >> $savemepath
                        for suf in dcd colvars.traj coor xsc; do
                           if [[ -f ${pref}-run.${suf} ]]; then
                              echo $t/$d/runfiles/${pref}-run.${suf} >> $savemepath
                           fi
                        done
                    fi
                fi
            fi
        done
	    cd ../..
    done
    cd $OWD
done

echo "Wrote `wc -l $saveme | cut -f1 -d' '` names to $saveme"
echo "Tarring to archive-${saveme}.tar ..."
tar vcf archive-${saveme}.tar -T $saveme
echo "done."
